// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using OnlineShop.Models;
using System;
using System.Collections.Generic;

namespace OnlineShop.Models
{
    public partial class CustomerDto
    {
        public CustomerDto()
        {
            CustomerAddresses = new HashSet<CustomerAddressDto>();
            SalesOrderHeaders = new HashSet<SalesOrderHeaderDto>();
        }

        public int CustomerID { get; set; }
        public bool NameStyle { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string CompanyName { get; set; }
        public string SalesPerson { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public Guid rowguid { get; set; }
        public DateTime ModifiedDate { get; set; }

        public virtual ICollection<CustomerAddressDto> CustomerAddresses { get; set; }
        public virtual ICollection<SalesOrderHeaderDto> SalesOrderHeaders { get; set; }
    }
}